# Generated by Django 3.1 on 2020-10-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('offer_price', models.IntegerField()),
                ('actual_price', models.IntegerField()),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
                ('brand', models.TextField()),
                ('storage', models.TextField()),
                ('ram', models.TextField()),
                ('display', models.TextField()),
                ('front_camera', models.TextField()),
                ('back_camera', models.TextField()),
                ('processor', models.TextField()),
                ('battery', models.TextField()),
                ('waranty', models.TextField()),
                ('offer', models.BooleanField(default=False)),
                ('rate', models.IntegerField()),
                ('count', models.IntegerField()),
                ('col', models.TextField()),
            ],
        ),
    ]
