# Generated by Django 3.1 on 2020-11-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobicart', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
