# Generated by Django 3.1 on 2020-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobicart', '0005_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(default='packing'),
        ),
    ]
