# Generated by Django 3.1 on 2020-12-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobicart', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.TextField(),
        ),
    ]
